
export const SCREENS = Object.freeze({
  WELCOME: 'WELCOME',
  WAITING_ROOM: 'WAITING_ROOM',
  RULES: 'RULES',
  OPTIONS: 'OPTIONS',
  GAME_LOBBY: 'GAME_LOBBY',
  FATE: 'FATE',
  ROUND_LOBBY: 'ROUND_LOBBY',
  QUESTION: 'QUESTION',
  REVEAL: 'REVEAL',
  THREAD_SEVERED: 'THREAD_SEVERED',
  FATE_RESULT: 'FATE_RESULT',
  LAST_DECK: 'LAST_DECK',
  FINAL_QUESTION: 'FINAL_QUESTION',
  FINAL_RESULT: 'FINAL_RESULT',
  FINAL_READING: 'FINAL_READING',
  GAME_OVER: 'GAME_OVER',
  RESULTS: 'RESULTS',
  CREDITS: 'CREDITS'
});
